### ISSUE TITLE
Python 3 version

### ISSUE THREAD

**Issue by rallen2010** [ari/moneyworks-cli#2]
Hi Ari,  I've just seen this project and have been porting to Python 3.  Almost have it working - i can replicate the functionality in the Read.me above the 'Advanced  Tasks" heading so far.  Changes are relatively simple - print is now print(), and urllib.quote_plus is now urllib.parse.quote_plus.  
I haven't used GitHub much -- so how do i keep this for others?  Branch it / fork it?

**Comment by ari** [comment]
Yes, create a branch here on github. I use this library for saltstack and at this time that's still python 2.7, so I'll not yet merge your branch back here until I can sort that out.

Thanks for your contribution.

**Comment by ari** [comment]
I pushed a first draft of the python3 upgrade
