### ISSUE TITLE
ImportError: No module named error

### ISSUE THREAD

**Issue by hvisage** [ari/moneyworks-cli#3]
HI there,

I seem to miss something to get it running:

(mw) ➜  moneyworks-cli git:(master) python
Python 2.7.10 (default, Feb  7 2017, 00:08:15)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from moneyworks import Moneyworks, Transaction, Email
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "moneyworks.py", line 6, in <module>
    import urllib.error
ImportError: No module named error
>>>

**Comment by ari** [comment]
This package has now been upgraded to python3. Please use that instead.
